### ISSUE TITLE
Lesson 3.01 missing a Snap image file

### ISSUE THREAD

**Issue by N-Lake** [TEALSK12/2nd-semester-introduction-to-computer-science#12]
There's a broken link for an image file of 
```
(pick random (1) to (10))
```
 in Snap in section 2 of the instructor's notes.

**Comment by hollasch** [comment]
This is a reference to https://bjc.berkeley.edu/bjc-r/img/lab-10/random-tree-buggy-code-snap.png, which yields a 403 Forbidden error.

This image is referenced from `units/3_unit/01_lesson/lesson.md`.

**Comment by aspiece** [comment]
Updated image.
