### ISSUE TITLE
Lesson 6.04 Do Now

### ISSUE THREAD

**Issue by degriff** [TEALSK12/2nd-semester-introduction-to-computer-science#129]
It appears that this Do Now is based more in Python 2.x and not 3.x. In 3.x, `keys()` returns `<class ‘dict_keys’>` which is not subscriptable. I believe that using subscripts is the cleanest way to print the 5 most frequent and 5 least frequent words from a sorted dictionary satisfying the bonus portion of the lab. In order to use subscripts, the return value from `keys()` needs to be cast to a list. I think that it would be helpful to highlight the differences between `dict_keys` and `list` in addition to the similarities.

**Comment by aspiece** [comment]
Great catch. Pending my next merge this will be updated. Including the Repl.it classroom for next year.
