### ISSUE TITLE
Lesson 6.04 - Typos in Green Eggs and Ham

### ISSUE THREAD

**Issue by degriff** [TEALSK12/2nd-semester-introduction-to-computer-science#130]
Line 1 should read: **I am Sam. I am Sam. Sam-I-am.**

Line 19 should read: **Would you like them with a mouse?** Changing **_then_** to **_them_** changes the most frequent word count.

**Comment by aspiece** [comment]
Updated. Thank you @degriff

**Comment by degriff** [comment]
The **_then_** was changed to **_them_** and did not update the out with corrected count.  The new count should be 12
