### ISSUE TITLE
Lesson 6.04 - Removing hyphen from Sam-I-am?

### ISSUE THREAD

**Issue by degriff** [TEALSK12/2nd-semester-introduction-to-computer-science#131]
Why is the hyphen getting removed from Sam-I-am in the example? When used in this manner, the character is not punctuation; it is creating a compound word. Some examples of other compound word created by connecting with a hyphen are mother-in-law, over-the-counter, and jack-in-the-box.

**Comment by aspiece** [comment]
Hello @degriff Pending merge, updated PPT and made sure that the Repli.it classroom is updated for next year. 
Thank you.
