### ISSUE TITLE
1.02 Suggestions

### ISSUE THREAD

**Issue by djocho** [TEALSK12/2nd-semester-introduction-to-computer-science#136]
Part 1 section 3 - there is no longer an expression that combines different types, so there is no longer an error message here.

I’ve been pulling all of the definitions (in this lesson: console, interpreter, float, integer, string, expression) and creating a “notes” document. It would be great to have one of these ready to go as a resource for students, perhaps divided out by lesson.

3 data types get defined here, but there is no follow up - for example the next day’s Do Now could be about identifying data types, or coming up with reasons someone might use each one… data types are both mundane and important and not understanding them comes back to bite you much later.

One thing this lab gets at is that the same operator works differently (or doesn’t work) for different data types, and formalizing this could be another place to solidify the class’ understanding of the types.

Finally, I’ve made investigating the % and ** operators an extension for each part of the lab (% appears in part 1, ** in part 2) for those who finish early

**Comment by ericatealsk12** [comment]
Suggestion:
Remove the 2 discussion questions in Part 1 section 3 in 1_unit/02_lesson/lesson.md and 1_unit/slidedecks/Intro Python 1.02 TEALS.pptx as there is no longer an error message
- What do you think the error message means?
- You can't combine different types!

If the curriculum team has the capacity to, add more data type exercises (for example, to Do Now 1.03) and extensions in Unit 1.
