### ISSUE TITLE
Lab 2.05 referring students to something they have not done and def

### ISSUE THREAD

**Issue by mscochrill** [TEALSK12/2nd-semester-introduction-to-computer-science#140]
Students are confused as the lab directions refer them to a lab we have never done. 

The PDF appears to be correct by not referring to this non-existent lab. 
This is from the cloned assignment. 
2) Remember the tic-tac-toe board we created in class? 
 # Tic-Tac-Toe

The cloned assignment also has def in the code but that has not been introduced to the students.

**Comment by aspiece** [comment]
@graceTeals As I was working through my issues assigned, I noticed that we need to make sure we update the following if necessary

Lab.docx
Slide deck
Repl.it Classroom (Need to be sure you are in the master course)

**Comment by graceTeals** [comment]
@aspiece , It looks like the the lab document (PDF, Git, and Docx) are all correct. The Lab appears to be correct on the slides as well. I wonder if @kenneychan  didn't fix these issues on 2/6?
