### ISSUE TITLE
Actual solutions to labs?

### ISSUE THREAD

**Issue by sjliam** [TEALSK12/2nd-semester-introduction-to-computer-science#147]
All info looks like the same info from the TEALS site, where are the actual solutions to any of the labs? TEALS resources are not as clear and concise as other programs such as code.org. There are missing example solutions and answer keys in just about every unit for second semester as well as APCSA This is very unorganized to say the least.

**Comment by aspiece** [comment]
Hello @sjliam, thank you so much for your feedback. The sample solutions can be found in the Additional Curriculum Materials that can be accessed from the TEALS Dashboard. We feel sample solutions and answer keys should be kept behind a password and not publicly available. Feel free to reach out to your regional manager if you are having trouble finding them. If we missed something, please let us know and we will see if we can't track it down for you and/or make sure we get it available as soon as possible. 

--Andrew

**Comment by sjliam** [comment]
Awesome! I found the one I was looking for. Thank you for your help!!


Demarion Hall
Technology Teacher | IDEA Judson College Preparatory
| demarion.hall@ideapublicschools.org<mailto:demarion.hall@ideapublicschools.org>
Join IDEA's Team and Family: Apply Today<https://www.ideapublicschools.org/careers> | Refer-A-Friend<https://app.jobvite.com/TalentNetwork/action/campaign/w/NjExNTE>
IDEA Celebrates 20 Years:  Click Here to Learn More<https://ideapublicschools.org/>

[http://ideapublicschools.smugmug.com/Socialmediabadges/Badges/i-tCswqkB/0/M/idea-M.png]<http://www.ideapublicschools.org> [http://ideapublicschools.smugmug.com/Socialmediabadges/Badges/i-HnFRKzh/0/L/facebook-L.png] <https://www.facebook.com/ideapublicschools>  [http://ideapublicschools.smugmug.com/Socialmediabadges/Badges/i-sV9mpgC/0/L/twitter-L.png] <https://twitter.com/IDEAschools>  [http://ideapublicschools.smugmug.com/Socialmediabadges/Badges/i-VDWdmsK/0/L/instagram-L.png] <http://instagram.com/IDEASchools>  [http://ideapublicschools.smugmug.com/Socialmediabadges/Badges/i-PgPChfH/0/L/linked-in-L.png] <https://www.linkedin.com/company/idea-public-schools>

IDEA Public Schools<https://ideapublicschools.org/> is celebrating 20 years of impact for students, families, staff and communities. During the last two decades, IDEA Public Schools has grown from a small school with 150 students to the fastest-growing network of tuition-free, Pre-K-12 public charter schools in the United States. Currently, the network serves nearly 53,000 college-bound students in 96 schools across Texas and Louisiana. IDEA has been recognized as a “Great Place to Work” and received national rankings on U.S. News & World Report’s Top High Schools lists. IDEA remains on-track to uphold its legacy of sending 100% of its graduates to college.

**Comment by aspiece** [comment]
@sjliam Of course.
