### ISSUE TITLE
All Units in 2nd semester intro to cs Gitbook are missing 

### ISSUE THREAD

**Issue by the-xx** [TEALSK12/2nd-semester-introduction-to-computer-science#166]
Can not find any units in the   2nd semester intro to cs Gitbook.
https://tealsk12.gitbook.io/intro-cs-2/

<img width="1166" alt="Screen Shot 2020-02-12 at 11 37 00 PM" src="https://user-images.githubusercontent.com/6083498/74411744-db013280-4df0-11ea-9617-ac3f9d42f2a4.png">

**Comment by aspiece** [comment]
Thank you @the-xx. we are working with Gitbook to get it resolved. We really apologize for this. Feel free to reference the Repository for now as we work through this.

**Comment by aspiece** [comment]
Hello @the-xx, , 

Gitbook is back up and running .

--Andrew
