### ISSUE TITLE
Do Now 2.4 part 2 is confusing

### ISSUE THREAD

**Issue by Love2Innovate** [TEALSK12/2nd-semester-introduction-to-computer-science#199]
The students are confused by the second part of Do Now 4.2, which asks them to run the following in the Console
```
len_a = len(a)
range(0, len(a))
```
The problem is that “len_a = len(a)” doesn’t print anything to the screen. It should have been just len(a), which would print ‘4’, the length of the array to the screen.

Another problem is range(0, len(a)) only prints ‘range(0, 4)’ to the screen in Python 3. That’s the range object. In Python 2, it would have printed the list of numbers in the range. 

So, It should be modified it to include
`list(range(0, len(a)))`
This would then print [0, 1, 2, 3] to the screen.

===============
Note that the issue has been reported and marked as resolved in Nov. 2019: https://github.com/TEALSK12/2nd-semester-introduction-to-computer-science/issues/88

However, I just used Do Now 4.2 today and used the materials from https://tealsk12.gitbook.io/intro-cs-2/unit4/lesson-1/do_now
and Part 2 of Do Now 4.2 is still there.
Plus, the 'len_a = len(a)' issue is not mentioned in the Nov. 2019 issue ticket.

I think Part 2 should be kept, but just include 'list(range(0,4))', since the students do need to know how to find out exactly what's included in a range object.

**Comment by aspiece** [comment]
This has been updated in a previous release.
