### ISSUE TITLE
Do Now 2.4 part 3 is unclear

### ISSUE THREAD

**Issue by Love2Innovate** [TEALSK12/2nd-semester-introduction-to-computer-science#201]
Do Now 2.4 Part 3 has the following text:
    "3. In your Console
        Use the range and len functions to make a for loop. (Remember that for loops iterate over lists)"

Most students did not even do this part. Make a for loop to do what? It doesn't say.

Yet, Part 2 has the following text:
"Use the range and len functions to make a for loop that loops through a."

But the two questions in Part 2 are meant to just understand the functionality of range and len.

Suggested edits:
1. Remove the reference to making a for loop from Part 2.
2. Rephrase Part 3 to be more specific:
"Use the range and len functions to make a for loop that prints each element of the list 'a'. (Remember that for loops iterate over lists)"

**Comment by aspiece** [comment]
This has been updated in previous release
