### ISSUE TITLE
404 Page Not Found on Lesson 2.07: Project

### ISSUE THREAD

**Issue by donny-nyc** [TEALSK12/2nd-semester-introduction-to-computer-science#227]
Under Lesson 2.07, accessed here: https://tealsk12.github.io/2nd-semester-introduction-to-computer-science/units/2_unit/07_lesson/lesson.md.html

There's a typo in the link for [Associated Readings 2.7](https://tealsk12.github.io/2nd-semester-introduction-to-computer-science/readings.md.html.html#associatedreadings/2.7) causing a `404` when clicked.

Currently (note the duplicate `.html`): https://tealsk12.github.io/2nd-semester-introduction-to-computer-science/readings.md.html.html#associatedreadings/2.7

Should probably be: https://tealsk12.github.io/2nd-semester-introduction-to-computer-science/readings.md.html#associatedreadings/2.7

![2020-07-12-170317_886x426_scrot](https://user-images.githubusercontent.com/2840641/87256543-a8239f00-c461-11ea-98ec-2555683a38a7.png)

**Comment by sdonahuebk** [comment]
Interestingly, the markup for lesson.md under `master` does not seem to have this extra text:

https://github.com/TEALSK12/2nd-semester-introduction-to-computer-science/raw/master/units/2_unit/07_lesson/lesson.md

**Comment by aspiece** [comment]
Tested this on https://tealsk12.github.io/2nd-semester-introduction-to-computer-science/units/2_unit/07_lesson/lesson.md.html

and it seems to be fixed. Sorry for any inconvenience.

Andrew
