### ISSUE TITLE
Lesson 1.04 - Too many concepts

### ISSUE THREAD

**Issue by Dan-TEALS** [TEALSK12/2nd-semester-introduction-to-computer-science#239]
There are too many concepts introduced in a single lesson - it's not feasible to cover the material as written in the lesson plan in 15 minutes. Also, why is variable swapping introduced in this lesson? It's only used in the Do Now and discussed briefly in the instruction, then not used again for the rest of the unit. There is no sorting in unit 1.

**Comment by aspiece** [comment]
Moving instruction to 2.01.
