### ISSUE TITLE
Lab 3 rubric link wrong

### ISSUE THREAD

**Issue by Dan-TEALS** [TEALSK12/2nd-semester-introduction-to-computer-science#247]
The link to the editable lab 3 rubric in the curriculum map opens the lab 2 rubric.

**Comment by aspiece** [comment]
@Dan-TEALS  which unit?

**Comment by Dan-TEALS** [comment]
Found it! On the Project 3 (Oregon Trail) Curriculum Map page, the _editable grading rubric_ link opens the Project 2 (Text Monster) rubric. Sorry about the incorrect issue title.

![Project 3 screenshot](https://user-images.githubusercontent.com/41020556/105535226-da814500-5cab-11eb-90db-d82902fbcccf.png)
