### ISSUE TITLE
Unit 2 BC Ogopogo Project Feedback

### ISSUE THREAD

**Issue by ericatealsk12** [TEALSK12/2nd-semester-introduction-to-computer-science#282]
Feedback from a volunteer:

An attempt was clearly made to start with the standard Unit 2 final Text Monster project and make simple changes to the specs to give it some Canada-specific reference points.  As the specs are now written, the project could be confusing for Intro to CS students.

**1. Directions:** The direction down is nonsensical in the setting (from the current Ogopogo starter code):

if user_input == "down":
    current_shore = user_lake[user_shore]
    if current_shore != "canal":
        print("Can't go there; there are no canal.")

"There are no canal" and the nonsensical direction "down" are strong hints that the word "stairs" was searched-and-replaced with the word "canal" everywhere in Text Monster's starter code. "Room" was replaced everywhere with "shore", "floor" was replaced with "lake".  Both of those replacements *could* be made to work, but it's not trivial.  

The Text Monster "left" and "right" commands might have to change to something like "clockwise" and "counterclockwise" to fit the lake theme. 

The specs should probably say specifically that if you go far enough, you wrap around the lake and end up where you started.  Maybe we'd have eight shores instead of four -- N, NE, E, SE, S, SW, W, and NW shores -- so that there's enough room for all the equivalent challenges from Text Monster.

**2. Canal:** Given how the three lakes are laid out on a map, better equivalent commands would be "north" and "south", and the plain "canal" entries could be "northward canal" and "southward canal".

However, that would create at least two new confusions.  The current lake shores are identified as "north", "south", "east" and "west", but the sample code doesn't seem to place the canals correctly in the north and south shores.  Maybe "canal north to Lake Okanagan", "canal south to Skaha Lake", "canal south to Vaseux Lake", and "canal north to Skaha Lake" could be made to work, but that's a bit trickier for beginning students to implement than simple up and down staircases like in Text Monster.

**3. Confusing project requirement to fit the lake theme:** "A shore can contain: a bouncy castle, a kayak, a paddle board, a beach chair, or nothing." This requirement does not make sense. Most of the rest of the specs are completely unchanged from what they are in Text Monster.  So according to all of those other remaining specs, the above list should really be "a canal, a sword, magic stones, a monster, a boss monster, a prize, or nothing".

**4. The Ogopogo theme:** Finally... the purpose of Text Monster is for a player to fight their way past three junior monsters and eventually kill the "boss monster" with a sword (and magic stones).  I'm not sure it makes sense to cast Ogopogo as an equivalent boss bad guy, and just kill it with a sword. The Lake Okanagan tourism industry might not approve...

Maybe it would be better to use a kayak paddle to lure Ogopogo to the bouncy castle, or find a video camera and a good light source somewhere and collect pictures of all the mythical monsters, or something along those lines.  But those game mechanics definitely need to be spelled out clearly in the specs -- or they should at least be mentioned!

**Comment by dvgrn** [comment]
[Checked in](https://github.com/TEALSK12/2nd-semester-introduction-to-computer-science/commit/afca76864cea45d6ab6a8d77033f584d26499675) revised specs and starter code for Ogopogo, and versions of starter code with checkpoints for Ogopogo and Text Monster.
