### ISSUE TITLE
Lesson 2.05 - Lists 2

### ISSUE THREAD

**Issue by jorystark** [TEALSK12/2nd-semester-introduction-to-computer-science#284]
Except for slicing, many of the techniques introduced involve methods, which the students don't learn until unit 7, and I'm concerned about introducing dot notation without an adequate explanation of what it signifies. As far as I can tell, the only reason to teach these methods is that they're needed for the text monster game, since I'm not aware of them being used again. Moving forward, I think I'm going to make the activity for 2.06 the unit project, come up with something else for an activity in 2.06, and move slicing to 2.04.

**Comment by aspiece** [comment]
Hello @jorystark ,

Great observation. Thank you for your feedback. 

Andrew
