### ISSUE TITLE
Lesson 1.05 code links are broken

### ISSUE THREAD

**Issue by davidrhmiller** [TEALSK12/2nd-semester-introduction-to-computer-science#3]
In Lesson 1.05 (https://tealsk12.gitbooks.io/2nd-semester-introduction-to-computer-science/content/units/1_unit/05_lesson/lesson.html) there are (at least) two places where the text references example buggy code. In each place, it links the anchor to

https://tealsk12.gitbooks.io/2nd-semester-introduction-to-computer-science/content/units/1_unit/05_lesson/code.py

When I click on that link, it doesn't go anywhere -- just keeps me on the same page I'm viewing.

**Comment by davidrhmiller** [comment]
Note that the links work properly from within the GitHub repository.

That is, the GitHub version of Lesson 1.05 (https://github.com/TEALSK12/2nd-semester-introduction-to-computer-science/blob/master/units/1_unit/05_lesson/lesson.md) links to a GitHub version of the example code (https://github.com/TEALSK12/2nd-semester-introduction-to-computer-science/blob/master/units/1_unit/05_lesson/code.py) and it is perfectly visible.

The problem arises when I start from the published GitBooks version of the lesson. Somehow when viewing it through GitBooks, the link to the code starts with the https://tealsk12.gitbooks.io host, and trying to load code.py from there fails.

**Comment by davidrhmiller** [comment]
Huh --- it's even weirder than I thought.

If I open a new browser window and navigate directly to https://tealsk12.gitbooks.io/2nd-semester-introduction-to-computer-science/content/units/1_unit/05_lesson/code.py it works fine.

But if I start at https://tealsk12.gitbooks.io/2nd-semester-introduction-to-computer-science/content/units/1_unit/05_lesson/lesson.html and then click on the hyperlinked word "code" in the sentence "... and example code to prepare students for analyzing and responding to errors", it doesn't work.

I am on a MacBook Pro running Chrome 
 Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by hollasch** [comment]
It also works if you launch the link in a new tab. For example, by holding down the control key when clicking on the "code" link. Other links on the page that _do_ work seem to have `_target='blank'` in their anchor HTML.
