### ISSUE TITLE
Lesson 1.01 wrong link?

### ISSUE THREAD

**Issue by jdonwells** [TEALSK12/2nd-semester-introduction-to-computer-science#318]
https://github.com/TEALSK12/2nd-semester-introduction-to-computer-science/blob/master/units/1_unit/01_lesson/lesson.md has this:

Decide which IDE will be used for the classroom for the semester. TEALS keeps a list of free and low-cost IDEs to use in our implementation guide

With a link that goes to https://www.tealsk12.org/implementation-guide-online/#20-2. However, there is not a list of low-cost IDEs.

**Comment by aspiece** [comment]
Thank you @jdonwells . We have added new guidance to our implementation guide. Thank you for pointing this out. I will update the lesson now.

Andrew
