### ISSUE TITLE
Unit Project 6.05: concerns, suggestions for revamp

### ISSUE THREAD

**Issue by davidrhmiller** [TEALSK12/2nd-semester-introduction-to-computer-science#33]
(Cross posted from [discussions forum][0])

I have some concerns about the [Unit 6 project (Guess Who)][1], and curious how other instructors have experienced it. We're scheduled to start it late this week or early next week. I'm looking for a few things:

a) Feedback on my concerns
b) Thoughts on whether/how we should revamp the project

Concerns about the incumbent project:

* The project is too easy. Here's my [sample implementation of the Unit 6 project][2]. The whole thing is 15 lines of code, plus 35 lines of data that I just copied in from the Lab handout and reformatted as a dictionary. I don't think I used any advanced techniques, just what we'd expect a clean student solution to look like. It's an OK length for a 1 day lab, maybe stretch it to 2. But there's not nearly enough there for a multi-day project.

* The "flavor-text" rubs me the wrong way. The game is the epitome of objectifying people, and the first attribute it highlights is gender. It doesn't specifically enforce binary gender, but all of the sample persons male or female. I don't have strong opinions on gender politics, but this feels like inviting trouble where it is unnecessary. We could change the target objects to cars, or shoes, or washing machines, or college classes, all of which have multiple properties.

* The program is a poor imitation of the actual game Guess Who. That game involves a physical board that displays all the characters at the start, and lets you ask boolean questions ("Is your person wearing glasses"). Then based on the answer you eliminate some people from contention, flipping over their cards. As the game goes on, you have a visibly shrinking set of candidates. It's not obvious what is a good way to replicate that experience in a text-only interface, and it's hard to allow players to ask open-ended questions like "Does your player look happy?". So it's just not that great a game.

* The data entry part of the project is tedious. The lab provides data for 5 characters in its example, and the rubric says you must have at least 5 characters. The game is pretty boring with only 5, but adding more is a matter of laboriously typing out all the names and attributes of those you wish to add. Some students will bristle at this, but still worse: some students will spend a lot of class time just doing data entry. That's a waste.

Thoughts on whether/how to revamp this. Here are some options:

* We could change the flavor-text, leave it as a 1-2 day lab, then move on to Unit 7 or Unit 8. I'm somewhat inclined to do this. Strawman flavor-text: objects are cars, attributes are manufacturer, number of doors, whether forward collision warning is standard/optional/unavailable, whether engine is gasoline/electric/hybrid. Make up fictional car names and/or manufacturers if need be.

* We could provide a larger data file in comma-separated value format, and ask the students to write code that parses it into the dictionary data structure. In general CSV parsing is a pain because of all the corner cases, but we can provide a data file where the parsing is easy -- splitting the file into lines, split each line on commas. Then they need to build up the dictionary of dictionaries. In the end the game is the same, but you could have more total objects in play, which requires more guesses. This could add a day or two to the project, and it is useful experience to have: basic data processing is a key bit of CS, and understanding that/how real-world data gets in an out of programs is a step the students haven't been exposed to.

* We could re-conceive the game as a Shopping Filter program. Anyone who has tried to shop on line, whether for a winter coat, an instructional course, or a thing to do on the weekend, has undoubtedly encountered the search-and-filter paradigm. You say you want a sweater and the site shows you 176 matching items, with a collection of check-boxes off to the side that let you narrow your search. You can filter by Brand, and select 1 or more allowable values. You can filter by price, by available size, by available color, etc. We could provide the students with a data file of the 176 sweaters and ask them to implement the shopping filters. The user is shown results 1-10 of 176, then asked how they want to filter. They select an attribute, and a list of allowable value (e.g. Color: green, red). The program applies the filters, displays results 1-10 of the ones that satisfy. The program allows the user to add, remove, or edit filters that are applied.<br>
This is both a real-world, familiar application and a more substantive undertaking. I would imagine this could take 4-6 days for the students to complete. They could also find and import their own data files from their favorite domains: athlete stats, movies, pokemon monsters, restaurants, etc. And they could extend it with a "sort-by" feature.<br>
The user interface could be a little tricky, but it's not too hard. We could provide it to them as a scaffolding to let them concentrate on the underlying data structures and processing.

 I'm leaning towards doing this for my own class:
1. Change flavor text to the car model domain.
2. Give them a data file with ~30 entries in CSV format.
3. Use fictional car manufacturers and model names.
4. Require them to write code to build up the dictionary from the CSV file.
5. Leave the task as "I just leased a car. Guess what car I'm driving"
6. Plan on 4 days for the Project.

Can anyone share their thoughts on and experience with this Lab/Project?

Thanks,
   David

[0]: https://forums.tealsk12.org/t/unit-project-6-05-concerns-suggestions-for-revamp/1977
[1]: https://tealsk12.gitbooks.io/2nd-semester-introduction-to-computer-science/content/units/6_unit/05_lesson/project.html
[2]: https://repl.it/@davidrhmiller/TEALS2018-Unit-6-Project-Guess-Who

**Comment by davidrhmiller** [comment]
I've built a new lesson as an alternative for this. Currently it's in a branch, will finish it up and make a formal pull request. But in case anybody is interested in getting a sneak peak, it's at:

https://github.com/TEALSK12/2nd-semester-introduction-to-computer-science/blob/shopping/units/6_unit/05b_lesson/project.md

**Comment by aspiece** [comment]
Thank you @davidrhmiller I am adding the option project. Great work here.
