### ISSUE TITLE
Unit 7 Pokemon project --starter code is missing

### ISSUE THREAD

**Issue by mscochrill** [TEALSK12/2nd-semester-introduction-to-computer-science#398]
The PDF and the page for the project both refer to starter code but there isn't any (again). 

The page says: Use classes to build off the implemented base class for Pokemon. Keep track of HP, Max AP, and type.
Here is some [starter_code].  [https://tealsk12.github.io/2nd-semester-introduction-to-computer-science/units/7_unit/05_lesson/project.md.html](url)

The PDF points to: [https://teals-introcs.gitbooks.io/2nd-semester-introduction-to-computer-science-pri/content/units/7_unit/05_lesson/starter_code.py](url). The message they get is: 404
Book teals-introcs/2nd-semester-introduction-to-computer-science-pri not found

**Comment by mscochrill** [comment]
Found here: https://github.com/TEALSK12/2nd-semester-introduction-to-computer-science/blob/master/units/7_unit/05_lesson/starter_code.py

Could someone please update it in the TEALS curriculum?

**Comment by Dan-TEALS** [comment]
Thanks for catching that! There are a few of those references to the GitBook still present in the curriculum.
