### ISSUE TITLE
Lab 2.05 missing the advertised example

### ISSUE THREAD

**Issue by davidrhmiller** [TEALSK12/2nd-semester-introduction-to-computer-science#4]
In section 3 of https://tealsk12.gitbooks.io/2nd-semester-introduction-to-computer-science/content/units/2_unit/05_lesson/lab.html it reads

> Create a quiz to help you choose which college you should go to (or another topic of your choice. See Example Below)

There is no related example shown below.

**Comment by aspiece** [comment]
Removed the call to the example
