### ISSUE TITLE
Ill-formed learning objectives in lesson 3.04

### ISSUE THREAD

**Issue by nathanielgranor** [TEALSK12/2nd-semester-introduction-to-computer-science#60]
Lesson 3.04 contains 3 learning objectives that use the illegal verb "understand" and are therefore not assessable by teachers:
Understand that changing a list in a function updates the list outside of the function
Understand that updating variables in a function does not affect the variable outside of the function
Understand global variables

These violate the norms taught in TEALS training and should be replaced. In particular, "understand global variables" is an egregious violation since it is not clear what level of understanding students should be able to demonstrate.

**Comment by aspiece** [comment]
All set
