### ISSUE TITLE
Associated Reading section 3.04 examples don't make sense

### ISSUE THREAD

**Issue by nathanielgranor** [TEALSK12/2nd-semester-introduction-to-computer-science#61]
Two problems in this section:
the "cat_twice" function example calls a "print_twice" function which is not defined.

Also, the text says "For example, outside print_twice, there is no such thing as bruce."
"Bruce" is not used or defined anywhere in this section and makes no sense in the text.

**Comment by aspiece** [comment]
Removed Reference to Reading.
