### ISSUE TITLE
Lessons 1.01 Sign Up Guide PDF Error

### ISSUE THREAD

**Issue by apfoerts** [TEALSK12/2nd-semester-introduction-to-computer-science#62]
![image](https://user-images.githubusercontent.com/12780104/49709025-36c99d80-fbe7-11e8-959f-9034e3a6a1af.png)
In the Sign Up Guide pdf found in Lesson 1.01, when you are creating your first Repl.it file the instructions say to search for python3. Searching python3 does not result in a python3 result however, just Python. This may be confusing to students worried about selecting the right language and I would update the screenshot

**Comment by kenneychan** [comment]
HI Bhavani,

Can you fix the .doc and .pdf file for this bug?

Thanks.

Kenney Chan
Curriculum Manager, TEALS
Computer Science in Every High School | tealsk12.org<http://tealsk12.org/> | Facebook<https://www.facebook.com/tealsk12>
TEALS in New York Times<http://www.nytimes.com/2012/10/01/technology/microsoft-sends-engineers-to-schools-to-encourage-the-next-generation.html?pagewanted=all> | CNN<http://www.cnn.com/2013/05/14/tech/innovation/computer-science-teals/> | Harvard Ed School<http://www.gse.harvard.edu/news/12/12/technology-education-and-literacy-schools> | Kentucky video<http://www.youtube.com/watch?v=ACq9oSlmPC8>

**Comment by aspiece** [comment]
All Set!!!
