### ISSUE TITLE
Do Now 5.01 Clarification

### ISSUE THREAD

**Issue by aimeerosato** [TEALSK12/2nd-semester-introduction-to-computer-science#75]
The links for the individual Unit 1, Lesson 1 sub lessons don't open into the actual lessons (they just get you the most general directory of all the units).

The numbering is also confusing.  Perhaps we can add a picture of the Unit 1, Lesson 1 menu so that people know where to click on the individual lessons.

**Comment by aimeerosato** [comment]
Looks like the same is true in other Do Nows in Unit 5.  The direct links don't take you to the curriculum sections listed and it would be helpful to turn some numbers into bullets for clarity.

**Comment by aspiece** [comment]
Fixed. ;)
