### ISSUE TITLE
Broken Link to project_file.py in Lesson 2.08

### ISSUE THREAD

**Issue by swkasica** [TEALSK12/2nd-semester-introduction-to-computer-science#79]
I just noticed the [link](https://github.com/TEALSK12/2nd-semester-introduction-to-computer-science/blame/f5a67d9d11e6d21cddd586d1b432f0a8a2b654f0/units/2_unit/08_lesson/lesson.md#L58
) is broken for "Text Monster Game - Example Code" in [`units/2_unit_08_lesson/lesson.md`](https://github.com/TEALSK12/2nd-semester-introduction-to-computer-science/blob/f5a67d9d11e6d21cddd586d1b432f0a8a2b654f0/units/2_unit/08_lesson/lesson.md)

![image](https://user-images.githubusercontent.com/2933702/52961391-b09ca680-334f-11e9-9422-14fbc4d3aee5.png)

**Comment by aspiece** [comment]
All Set
