### ISSUE TITLE
Health in the Unit 3 project (Oregon Trail) sample solution doesn't match spec

### ISSUE THREAD

**Issue by mrmckinley** [TEALSK12/2nd-semester-introduction-to-computer-science#84]
The project spec for the Unit 3 project states that "The player's health randomly decreases 2 times during the month." The sample solution gives the player a 2 in 30 chance of falling ill on any given day (so it doesn't guarantee that a player falls ill twice in a month).

I think the ideal solution would be to update the spec to match the sample solution (e.g., "On average, the player's health will randomly decrease twice during a month" and clarify that this means on any given day, the player has a 1 in 15 chance of falling ill). Trying to make the player fall ill exactly twice during a month (as outlined in the spec) might be overly complicated for the current skill level of students.

**Comment by aspiece** [comment]
All set. Thank you for the feedback.
