### ISSUE TITLE
Unit 2 - Clarify common misunderstanding of how `==` and `or` behave

### ISSUE THREAD

**Issue by mrmckinley** [TEALSK12/2nd-semester-introduction-to-computer-science#85]
A common misunderstanding among students that I've noticed is to write code like `if animal == 'cat' or 'dog':` 

I think it would be beneficial to explicitly teach that while syntactically correct code, it does not behave as expected. Here's what I propose:

In Lab 2.03 section 1, add the following two items to what the students are asked to predict and test:

    >>> animal = 'mouse'
    >>> animal == 'cat' or 'dog'

and

    >>> animal = 'mouse'
    >>> animal == 'cat' or animal == 'dog'

Revisit the concept in Lesson 2.04. During the lecture/class discussion show the following code:

    animal = input("What is your favorite animal?")
    if animal == 'cat' or 'dog':
        print("A great pet!")
    else:
       print("Good choice")

Give students time to predict the output for various inputs, discuss why the code is buggy, and then fix it together as a class. Before I submit a pull request, I would appreciate some assistance refining the language

**Comment by hawkerm** [comment]
In a later unit when lists are introduced, it'd be good to revisit this too and show how to condense the statement back down to how they would expect it to work again:

```
if animal in ['cat', 'dog']:
    print("A great pet!")
```

**Comment by aspiece** [comment]
It's all been added. Thank  you for your feedback!
