### ISSUE TITLE
Code contracts - use "arguments" instead of "inputs"

### ISSUE THREAD

**Issue by mrmckinley** [TEALSK12/2nd-semester-introduction-to-computer-science#86]
Unit 3 introduces code contracts, which are a simplified version of docstrings used in real-world code (e.g., [Google-style docstrings](https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html#example-google))

I propose that "Arguments" be used instead of "Inputs" for three reasons:

1. It reinforces language used in the lesson
2. Documentation on python.org (and in third-party modules) uses "argument" or "parameter" instead of "input"
3. It avoids confusion with user input / the `input` function

**Comment by aspiece** [comment]
Thank you @mrmckinley  I have updated all of Unit 3 references to inputs.
