### ISSUE TITLE
4.02 - Do Now Part 2 issues

### ISSUE THREAD

**Issue by mrmckinley** [TEALSK12/2nd-semester-introduction-to-computer-science#88]
Part 2 of the Do Now and the instructor's notes use the Python 2 behavior of `range` (generating a list of values). In Python 3, `range` no longer returns a list of values.

In the Do Now Students are asked to write down the return value of `range(0, len(a))` is. This will probably be confusing to students, as it returns a `range` object (and *not* a list as the instructor's notes say). 

I suggest that Part 2 be removed entirely or added as a bonus/enrichment (e.g., "What is the return type of range(1, 10)? Did anything surprise you?"). If done as enrichment, it could lead into a discussion about why `range` doesn't simply return a list of values.

**Comment by aspiece** [comment]
Thank you it has been removed.
