### ISSUE TITLE
Pokemon Project Mistakes

### ISSUE THREAD

**Issue by jsonpar** [TEALSK12/2nd-semester-introduction-to-computer-science#94]
In the project writeup for the pokemon assignment, several pokemon's names are spelled wrong (Bulbasoar instead of Bulbasaur, Polywag instead of Poliwag, Ninetails instead of Ninetales, and Charmainder instead of Charmander).

Also in the example print statement, it says

> Ash is attacking. Bulbosaur used Bubble and did 20 damage.

despite Bulbasaur being a Grass type and Bubble being a Water type attack.

Finally, this says 

>  2/3 the time they should file. 1/6 of the time they should heal and 1/6 of the time they should switch pokemon. 

which I believe should say 2/3 of the time a user should attack.

I can submit a PR with these fixes if I can get access (I'm an upcoming volunteer for the 2019-2020 school year) or I'd be okay with someone else making them.

**Comment by aspiece** [comment]
Hello @jsonpar Feel free to put in a PR anytime. I would be happy to review and merge it. I will leave this open and get to it asap . I have been catching up the issues and getting the class ready for 2nd semester.

**Comment by aspiece** [comment]
All set. Thank you
