### ISSUE TITLE
Lesson 2.01: Binary Day

### ISSUE THREAD

**Issue by aimeerosato** [TEALSK12/2nd-semester-introduction-to-computer-science#97]
Can this be more explicit about why it makes sense to talk about binary at this point in the curriculum?  I believe it could use greater context on the _why_ it is included here (both in the curriculum in general and why at the start of Unit 2).

**Comment by aspiece** [comment]
It looks as though there is some verbiage to lead a discussion with students on how bunary relates to Variables and data types. I am going to update the formatting now and add a video on Binary to help the new teacher understand how this is connected. It will also gives the volunteer of an example to explain binary.
